version: "3"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: shopify
      POSTGRES_PASSWORD: shopify
      POSTGRES_DB: shopify
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "shopify"]
      interval: 5s
      retries: 5
    restart: always
    ports:
      - 5432:5432

  # web-server:
  #   build:
  #     context: ../backend
  #     dockerfile: Dockerfile
  #   container_name: web-backend
  #   volumes:
  #     - ../backend/src:/home/node/app/backend/src
  #     - ../frontend:/home/node/app/frontend
  #     - ../data:/home/node/app/data
  #   env_file:
  #     - ../backend/.env
  #   expose:
  #     - "3000"
  #   ports:
  #     - "3000:3000"
  #   command: npm start
  #   depends_on:
  #     - postgres

volumes:
  postgres-db-volume:
